/**
 * Comprehensive Legal Metrology (Packaged Commodities) Rules Repository
 * 
 * This seed file provides an extensive collection of compliance rules based on:
 * - Legal Metrology (Packaged Commodities) Rules, 2011
 * - Official amendments and notifications
 * - Department of Consumer Affairs, Government of India
 * 
 * Source: https://consumeraffairs.gov.in/pages/legal-metrology-act
 * 
 * IMPORTANT:
 * - All rules include official legal references
 * - Applicability conditions prevent rule application to non-applicable products
 * - Many complex requirements are marked MANUAL_REVIEW or REQUIRES_OFFICER_REVIEW
 * - Rules are created with upsert logic to preserve existing data
 */

export const complianceRulesSeed = [
  // ==================== MANDATORY DECLARATION RULES ====================
  {
    ruleId: 'LMPC_MFG_NAME_001',
    title: 'Manufacturer/Packer Name Declaration',
    description: 'Name of the manufacturer or packer must be clearly declared on the package.',
    category: 'MANDATORY_DECLARATION',
    subCategory: 'Manufacturer Details',
    declaration: 'manufacturerName',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR-based detection',
    severity: 'critical',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: false,
    legalReference: 'Rule 5(1) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_MFG_ADDRESS_002',
    title: 'Manufacturer/Packer Address Declaration',
    description: 'Address (postal/contact details) of the manufacturer or packer must be declared.',
    category: 'MANDATORY_DECLARATION',
    subCategory: 'Manufacturer Details',
    declaration: 'manufacturerAddress',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR-based detection with manual verification recommended',
    severity: 'major',
    automationLevel: 'SEMI_AUTOMATED',
    officerReviewRequired: true,
    legalReference: 'Rule 5(1) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_COMMODITY_NAME_006',
    title: 'Common/Generic Name of Commodity',
    description: 'The commodity name or common description must be declared in principal display panel.',
    category: 'PRODUCT_IDENTIFICATION',
    subCategory: 'Commodity Naming',
    declaration: 'commodityName',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR detection and keyword matching',
    severity: 'critical',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: false,
    legalReference: 'Rule 3(1) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_NET_QUANTITY_007',
    title: 'Net Quantity Declaration',
    description: 'Net quantity (weight, volume, or count) must be declared in standard units.',
    category: 'QUANTITY_DECLARATION',
    subCategory: 'Net Quantity',
    declaration: 'netQuantity',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR-based numerical extraction',
    severity: 'critical',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: false,
    expectedKeywords: ['net', 'quantity', 'wt', 'weight', 'vol', 'volume', 'ml', 'l', 'gm', 'kg', 'pcs', 'pieces'],
    allowedUnits: ['g', 'kg', 'mg', 'ml', 'l', 'pcs', 'pieces', 'pairs', 'count'],
    legalReference: 'Rule 4(1) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_QUANTITY_UNIT_008',
    title: 'Net Quantity in Standard Unit',
    description: 'Net quantity must be expressed in standard metric or number format as applicable.',
    category: 'QUANTITY_DECLARATION',
    subCategory: 'Quantity Units',
    declaration: 'netQuantityUnit',
    required: true,
    validationType: 'UNIT',
    validationMethod: 'Pattern matching for standard units',
    severity: 'major',
    automationLevel: 'FULLY_AUTOMATED',
    officerReviewRequired: false,
    expectedPattern: '^(\\d+(\\.\\d+)?\\s*(g|kg|mg|ml|l|pcs|pieces|pairs|count))$',
    allowedUnits: ['g', 'kg', 'mg', 'ml', 'l', 'pcs', 'pieces', 'pairs', 'count'],
    legalReference: 'Rule 4(2) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== PRICE DECLARATION RULES ====================
  {
    ruleId: 'LMPC_MRP_DECLARATION_009',
    title: 'MRP Declaration',
    description: 'Maximum Retail Price must be declared on the package in Indian Rupees.',
    category: 'PRICE_DECLARATION',
    subCategory: 'MRP Declaration',
    declaration: 'mrp',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR-based numerical extraction with currency symbol detection',
    severity: 'critical',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: false,
    expectedPattern: '^[₹]?\\s*\\d+(\\.\\d{1,2})?$',
    expectedKeywords: ['mrp', 'maximum retail price', 'maximum sale price', 'msp', '₹', 'rupees', 'rs'],
    legalReference: 'Rule 6(1) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_MRP_FORMAT_010',
    title: 'MRP Format Validation',
    description: 'MRP should follow standard format with currency symbol and two decimal places.',
    category: 'PRICE_DECLARATION',
    subCategory: 'MRP Format',
    declaration: 'mrp',
    required: true,
    validationType: 'FORMAT',
    validationMethod: 'Regular expression pattern matching',
    severity: 'major',
    automationLevel: 'FULLY_AUTOMATED',
    officerReviewRequired: false,
    expectedPattern: '^[₹]?\\s*\\d+(\\.\\d{1,2})?\\s*$',
    legalReference: 'Rule 6(2) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_UNIT_SALE_PRICE_016',
    title: 'Unit Sale Price Declaration',
    description: 'Unit Sale Price should be declared where applicable (e.g., price per kg for loose commodities).',
    category: 'PRICE_DECLARATION',
    subCategory: 'Unit Price',
    declaration: 'unitSalePrice',
    required: false,
    validationType: 'PRESENCE',
    validationMethod: 'OCR detection with manual verification',
    severity: 'minor',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: true,
    expectedPattern: '^[₹]?\\s*\\d+(\\.\\d{1,2})?\\s*(/|per)?\\s*(kg|g|l|ml|unit|piece)?',
    legalReference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - as amended',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      unitSalePriceApplicable: true,
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== DATE DECLARATION RULES ====================
  {
    ruleId: 'LMPC_DATE_MFG_PACK_011',
    title: 'Date of Manufacture/Packing Declaration',
    description: 'Month and year of manufacture or packing must be declared for perishable commodities.',
    category: 'DATE_DECLARATION',
    subCategory: 'Manufacturing Date',
    declaration: 'dateOfManufacture',
    required: false,
    validationType: 'PRESENCE',
    validationMethod: 'OCR-based date detection with format validation',
    severity: 'major',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: true,
    expectedPattern: '^(0[1-9]|1[0-2])/(20\\d{2})$',
    expectedKeywords: ['mfg', 'manufactured', 'packing date', 'packed on', 'date of manufacture', 'date of packing'],
    legalReference: 'Rule 3(1)(ii) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['Food', 'Beverage', 'Cosmetics', 'Personal Care'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_BEST_BEFORE_012',
    title: 'Best Before/Expiry Date Declaration',
    description: 'Best Before or Expiry date must be clearly marked for commodities where shelf life is applicable.',
    category: 'DATE_DECLARATION',
    subCategory: 'Best Before Date',
    declaration: 'bestBeforeDate',
    required: false,
    validationType: 'PRESENCE',
    validationMethod: 'OCR-based date detection',
    severity: 'major',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: true,
    expectedPattern: '^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/(20\\d{2})$',
    expectedKeywords: ['best before', 'expiry', 'expires on', 'use by', 'bb date'],
    legalReference: 'Rule 3(1)(ii) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      bestBeforeApplicable: true,
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== IMPORTED PRODUCT RULES ====================
  {
    ruleId: 'LMPC_IMPORTER_DETAILS_003',
    title: 'Importer Details Declaration',
    description: 'Name and address of the importer must be declared on packages of imported products.',
    category: 'IMPORTED_PRODUCT',
    subCategory: 'Importer Information',
    declaration: 'importerDetails',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR detection with manual verification',
    severity: 'critical',
    automationLevel: 'SEMI_AUTOMATED',
    officerReviewRequired: true,
    legalReference: 'Rule 5(2) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      isImported: true,
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_COUNTRY_ORIGIN_004',
    title: 'Country of Origin Declaration',
    description: 'Country of origin must be clearly declared for imported products.',
    category: 'IMPORTED_PRODUCT',
    subCategory: 'Country of Origin',
    declaration: 'countryOfOrigin',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR detection with country name/code matching',
    severity: 'major',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: false,
    expectedKeywords: ['country of origin', 'made in', 'product of', 'imported from'],
    legalReference: 'Rule 3(1)(iii) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      isImported: true,
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_ECOMMERCE_DECLARATION_020',
    title: 'E-commerce Product Listing Declaration',
    description: 'All mandatory declarations must be available in e-commerce product listings.',
    category: 'E_COMMERCE',
    subCategory: 'Online Product Listing',
    declaration: 'eCommerceDeclarations',
    required: false,
    validationType: 'COMPLETENESS',
    validationMethod: 'Manual verification of e-commerce listing',
    severity: 'major',
    automationLevel: 'MANUAL_REVIEW',
    officerReviewRequired: true,
    legalReference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - E-commerce amendments',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {},
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== CONSUMER INFORMATION RULES ====================
  {
    ruleId: 'LMPC_CONSUMER_CARE_013',
    title: 'Consumer Care Contact Details',
    description: 'Consumer care phone number or email must be available on the package.',
    category: 'CONSUMER_INFORMATION',
    subCategory: 'Consumer Contact',
    declaration: 'consumerCare',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR detection with phone/email format validation',
    severity: 'major',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: false,
    expectedKeywords: ['consumer care', 'customer care', 'helpline', 'toll free', 'contact us', 'phone', 'email'],
    legalReference: 'Rule 3(1)(iv) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_CONTACT_PHONE_014',
    title: 'Consumer Care Phone Number Format',
    description: 'Phone number should be in a valid format (10 digits for India or toll-free format).',
    category: 'CONSUMER_INFORMATION',
    subCategory: 'Phone Number',
    declaration: 'consumerCarePhone',
    required: false,
    validationType: 'FORMAT',
    validationMethod: 'Regular expression validation for Indian phone numbers',
    severity: 'minor',
    automationLevel: 'FULLY_AUTOMATED',
    officerReviewRequired: false,
    expectedPattern: '^(\\+91[-.]?)?([0-9]{10}|180[0-9]{7,8})$',
    legalReference: 'Rule 3(1)(iv) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_CONTACT_EMAIL_015',
    title: 'Consumer Care Email Format Validation',
    description: 'Email address should follow a valid format.',
    category: 'CONSUMER_INFORMATION',
    subCategory: 'Email Address',
    declaration: 'consumerCareEmail',
    required: false,
    validationType: 'FORMAT',
    validationMethod: 'Regular expression pattern matching',
    severity: 'minor',
    automationLevel: 'FULLY_AUTOMATED',
    officerReviewRequired: false,
    expectedPattern: '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$',
    legalReference: 'Rule 3(1)(iv) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== DIMENSION DECLARATION RULES ====================
  {
    ruleId: 'LMPC_DIMENSIONS_017',
    title: 'Product Dimensions Declaration',
    description: 'Dimensions of the product should be declared where relevant (e.g., for apparel, furniture).',
    category: 'DIMENSION_DECLARATION',
    subCategory: 'Product Dimensions',
    declaration: 'dimensions',
    required: false,
    validationType: 'PRESENCE',
    validationMethod: 'Manual review and OCR detection',
    severity: 'minor',
    automationLevel: 'SEMI_AUTOMATED',
    officerReviewRequired: true,
    expectedKeywords: ['dimension', 'size', 'length', 'width', 'height', 'cm', 'inches'],
    allowedUnits: ['cm', 'inches', 'm', 'mm', 'inches'],
    legalReference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Category-specific provisions',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      dimensionsRelevant: true,
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== READABILITY RULES ====================
  {
    ruleId: 'LMPC_READABILITY_018',
    title: 'Declaration Text Readability',
    description: 'Declarations should be clearly visible, legible, and not obscured.',
    category: 'READABILITY',
    subCategory: 'Text Visibility',
    declaration: 'readability',
    required: true,
    validationType: 'READABILITY',
    validationMethod: 'Image quality analysis and OCR confidence scoring',
    severity: 'major',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: true,
    legalReference: 'Rule 3(4) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== FONT SCREENING RULES ====================
  {
    ruleId: 'LMPC_FONT_SCREENING_019',
    title: 'Declaration Text Font Size Screening',
    description: 'Declaration text may have a potentially small font size that requires officer review.',
    category: 'FONT_SCREENING',
    subCategory: 'Text Size Verification',
    declaration: 'fontSizeScreening',
    required: false,
    validationType: 'FONT_SCREENING',
    validationMethod: 'Image-based font size estimation (AI-assisted, requires calibration)',
    severity: 'major',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: true,
    legalReference: 'Rule 3(4) of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== PLACEMENT AND DISPLAY RULES ====================
  {
    ruleId: 'LMPC_PLACEMENT_020',
    title: 'Declaration Placement and Visibility',
    description: 'Declarations should be placed on principal display panel and be clearly visible.',
    category: 'PLACEMENT_AND_DISPLAY',
    subCategory: 'Display Requirements',
    declaration: 'placement',
    required: true,
    validationType: 'PLACEMENT',
    validationMethod: 'Manual review of package image',
    severity: 'major',
    automationLevel: 'MANUAL_REVIEW',
    officerReviewRequired: true,
    legalReference: 'Rule 3 of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== CONFLICT DETECTION RULES ====================
  {
    ruleId: 'LMPC_CONFLICT_MRP_021',
    title: 'Conflicting MRP Declarations',
    description: 'Multiple different MRP values detected on the package, indicating possible labeling error.',
    category: 'MANDATORY_DECLARATION',
    subCategory: 'Conflict Detection',
    declaration: 'mrp',
    required: false,
    validationType: 'CONFLICT',
    validationMethod: 'Text extraction and value comparison',
    severity: 'major',
    automationLevel: 'FULLY_AUTOMATED',
    officerReviewRequired: true,
    legalReference: 'Rule 6 of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_CONFLICT_QTY_022',
    title: 'Conflicting Quantity Declarations',
    description: 'Multiple different quantity values detected, indicating possible labeling inconsistency.',
    category: 'QUANTITY_DECLARATION',
    subCategory: 'Conflict Detection',
    declaration: 'netQuantity',
    required: false,
    validationType: 'CONFLICT',
    validationMethod: 'Text extraction and value comparison',
    severity: 'major',
    automationLevel: 'FULLY_AUTOMATED',
    officerReviewRequired: true,
    legalReference: 'Rule 4 of Legal Metrology (Packaged Commodities) Rules, 2011',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['ALL'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },

  // ==================== CATEGORY SPECIFIC RULES ====================
  {
    ruleId: 'LMPC_FOOD_ALLERGEN_023',
    title: 'Food Allergen Declaration',
    description: 'Known allergens must be declared prominently for food products.',
    category: 'CATEGORY_SPECIFIC',
    subCategory: 'Food Safety',
    declaration: 'allergenDeclaration',
    required: false,
    validationType: 'PRESENCE',
    validationMethod: 'OCR detection with allergen keyword matching',
    severity: 'critical',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: true,
    expectedKeywords: ['allergen', 'contains', 'may contain', 'nuts', 'gluten', 'dairy', 'shellfish', 'sesame'],
    legalReference: 'Food Safety and Standards (Labeling and Display) Regulations, 2020',
    legalSource: 'FSSAI, Government of India',
    sourceDocument: 'Food Safety and Standards (Labeling and Display) Regulations, 2020',
    officialSourceName: 'FSSAI',
    officialSourceUrl: 'https://fssai.gov.in',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['Food', 'Beverage'],
    },
    version: '2026.1',
    effectiveDate: new Date('2020-01-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_APPAREL_SIZE_024',
    title: 'Apparel Size Declaration',
    description: 'Size must be clearly declared for readymade garments.',
    category: 'CATEGORY_SPECIFIC',
    subCategory: 'Apparel Information',
    declaration: 'apparelSize',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR detection of size markings',
    severity: 'major',
    automationLevel: 'AI_ASSISTED',
    officerReviewRequired: false,
    expectedKeywords: ['size', 's', 'm', 'l', 'xl', 'xxl', '28', '30', '32'],
    legalReference: 'Legal Metrology (Packaged Commodities) Rules, 2011 - Textiles Schedule',
    legalSource: 'Department of Consumer Affairs, Government of India',
    sourceDocument: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    officialSourceName: 'Department of Consumer Affairs',
    officialSourceUrl: 'https://consumeraffairs.gov.in/pages/legal-metrology-act',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['Readymade Garments', 'Textiles'],
    },
    version: '2026.1',
    effectiveDate: new Date('2011-07-01'),
    active: true,
  },
  {
    ruleId: 'LMPC_COSMETIC_INGREDIENTS_025',
    title: 'Cosmetic Ingredients/Composition',
    description: 'Key ingredients and composition must be declared for cosmetic products.',
    category: 'CATEGORY_SPECIFIC',
    subCategory: 'Cosmetic Information',
    declaration: 'cosmeticIngredients',
    required: true,
    validationType: 'PRESENCE',
    validationMethod: 'OCR detection with manual verification',
    severity: 'major',
    automationLevel: 'SEMI_AUTOMATED',
    officerReviewRequired: true,
    legalReference: 'Drugs and Cosmetics Rules, 1945 - Amended Schedule M',
    legalSource: 'Ministry of Health and Family Welfare, Government of India',
    sourceDocument: 'Drugs and Cosmetics Rules, 1945',
    officialSourceName: 'Ministry of Health and Family Welfare',
    officialSourceUrl: 'https://www.indiacode.nic.in',
    lastVerifiedDate: new Date('2026-01-01'),
    applicabilityConditions: {
      applicableCategories: ['Cosmetics', 'Personal Care'],
    },
    version: '2026.1',
    effectiveDate: new Date('1945-01-01'),
    active: true,
  },
];

export default complianceRulesSeed;
