import 'dotenv/config';
import './config/env.js';
import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import path from 'path';
import { fileURLToPath } from 'url';
import { connectDatabase } from './config/db.js';
import authRoutes from './routes/auth.js';
import inspectionRoutes from './routes/inspections.js';
import ruleRoutes from './routes/rules.js';
import productRoutes from './routes/products.js';
import analyticsRoutes from './routes/analytics.js';
import reportRoutes from './routes/reports.js';
import { notFound, errorHandler } from './middleware/error.js';
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' })); app.use(express.json({ limit: '2mb' })); app.use(morgan('dev'));
const __dirname = path.dirname(fileURLToPath(import.meta.url)); app.use('/uploads', express.static(path.resolve(__dirname, '../uploads')));
app.get('/api/health', (req, res) => res.json({ ok: true, service: 'PackCheck AI API' }));
app.use('/api/auth', authRoutes); app.use('/api/inspections', inspectionRoutes); app.use('/api/rules', ruleRoutes); app.use('/api/products', productRoutes); app.use('/api/analytics', analyticsRoutes); app.use('/api/reports', reportRoutes);
app.use(notFound); app.use(errorHandler);
const port = process.env.PORT || 5000;
if (process.env.NODE_ENV !== 'test') connectDatabase().catch(error => console.error('Database unavailable:', error.message));
app.listen(port, () => console.log(`API listening on http://localhost:${port}`));
export default app;
